### RARITYLITE CONFIGURATIONS

permission:
  message: "&cYour not have permission."
console:
  message: "[RarityLite] You are not player!"
info:
  message:
    - "&aRarityLite v1.5.1"
    - "&r"
    - "&c<Require> &8&l| &6[Optional]"
    - "&a/rtl help | to see all commands!"
    - "&a/rtl <rarity> [glow] | make item to rarity!"
    - "&a/rtl list | to see all rarity"
    - "&a/rtl flag | to hide flags (enchant, dye, unbreakable, etc.)"
    - "&a/rtl unbreakable | make item to unbreakable"
    - "&a/rtl glow | make item to glow"
    - "&a/rtl reload | to reload configulation"
    - "&a"
    - "&aExample | &e/rtl uncommon glow"
list:
  message: "&aRarity List: %rarity%"
reload:
  message: "&aRarityLite v1.5.1 Reloaded!"
hold_item:
  message: "&cPlease hold item to make rarity!"
hide_flags:
  message: "&aSuccessfully to hide flags!"
  flags:
    - HIDE_ENCHANTS
    - HIDE_ATTRIBUTES
    - HIDE_DESTROYS
    - HIDE_DYE
    - HIDE_PLACED_ON
    - HIDE_POTION_EFFECTS
    - HIDE_UNBREAKABLE
unbreakable:
  message: "&aSuccessfully apply &9&lUNBREAKABLE"
glow:
  message: "&aSuccessfully apply glow to item"

## Blocked Config ## Effect on anvil, block place, taming, right click
blocked:
  name: # Blocked prevent has name?
    - "&aEnchanted"
    - "&4MyName"
  lore: # Blocked prevent has lore?
    - "&4&lSUPREME"
    - "&7Mylore"
    - "&cThis item can't be placing"
  flags: # Blocked prevent has flags?
    - HIDE_PLACED_ON
    - HIDE_ENCHANTS

## Pick Up Config ## Effect on spawning item, pickup, drop, craft, open chest, etc. (Use give command not working)
pickup: ## Check your blocked first to use this
  default:
    prefixName: "&f"
    suffixName: "&r"
    loreName:
      - "&f&lCOMMON"
    glowing: false # please check blocked config first to use this
    unbreakable: false
    flags: [] # please check blocked config first to use this
  ## USE MATERIAL ID
  custom: # Example here!
    NETHER_STAR:
      prefixName: "&6"
      suffixName: "&r"
      loreName:
        - "&6&lLEGENDARY"
      glowing: false # i think nether star is already glowing!
      unbreakable: false
      flags: []

    NETHERITE_INGOT:
      prefixName: "&9Enchanted " # Enchanted Netherite Ingot
      suffixName: "&r"
      loreName:
        - "&9&lRARE"
      glowing: true
      unbreakable: false
      flags:
        - HIDE_ENCHANTS # can't use this? go check blocked config first!

rarity: ## You can add your own rarity or remove!
  myrarity:
    prefixName: "&cMyCustomRarity "
    suffixName: " &r"
    loreName:
      - "&c&lCustomRarity"
    success: "&aItem Enchanted to &c&lCustomRarity"
    flags:
      - HIDE_ENCHANTS
    unbreakable: false

  common:
    prefixName: "&fEnchanted "
    suffixName: " &r"
    loreName:
      - "&f&lCOMMON"
    success: "&aItem Enchanted to &f&lCOMMON"
    flags:
      - HIDE_ENCHANTS
    unbreakable: false

  uncommon:
    prefixName: "&aEnchanted "
    suffixName: " &r"
    loreName:
      - "&a&lUNCOMMON"
    success: "&aItem Enchanted to &a&lUNCOMMON"
    flags:
      - HIDE_ENCHANTS
    unbreakable: false

  rare:
    prefixName: "&9Enchanted "
    suffixName: " &r"
    loreName:
      - "&9&lRARE"
    success: "&aItem Enchanted to &9&lRARE"
    flags:
      - HIDE_ENCHANTS
    unbreakable: false

  epic:
    prefixName: "&5Enchanted "
    suffixName: " &r"
    loreName:
      - "&5&lEPIC"
    success: "&aItem Enchanted to &5&lEPIC"
    flags:
      - HIDE_ENCHANTS
    unbreakable: false

  legendary:
    prefixName: "&6Enchanted "
    suffixName: " &r"
    loreName:
      - "&6&lLEGENDARY"
    success: "&aItem Enchanted to &6&lLEGENDARY"
    flags:
      - HIDE_ENCHANTS
    unbreakable: false

  mythical:
    prefixName: "&dEnchanted "
    suffixName: " &r"
    loreName:
      - "&d&lMYTHICAL"
    success: "&aItem Enchanted to &d&lMYTHICAL"
    flags:
      - HIDE_ENCHANTS
    unbreakable: false

  divine:
    prefixName: "&bEnchanted "
    suffixName: " &r"
    loreName:
      - "&b&lDIVINE"
    success: "&aItem Enchanted to &b&lDIVINE"
    flags:
      - HIDE_ENCHANTS
    unbreakable: false

  special:
    prefixName: "&cEnchanted "
    suffixName: " &r"
    loreName:
      - "&c&lSPECIAL"
    success: "&aItem Enchanted to &c&lSPECIAL"
    flags:
      - HIDE_ENCHANTS
    unbreakable: false