name: RarityLite
version: '${project.version}'
main: me.adivise.raritylite.Raritylite
api-version: 1.19
authors: [ Adivise ]
description: this plugins make you easy life to get enchanted items
commands:
  enchanted:
    description: select rarity and enchanted
    permission: raritylite.enchanted
    permission-message: You do not have permission.